// <auto-generated />
namespace TaskLogger.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class extendedUserTaskEntryClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extendedUserTaskEntryClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201503140844251_extendedUserTaskEntryClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
